### ISSUE TITLE
signup 2x with same email

### ISSUE THREAD

**Issue by VForsmann** [tillhoffmann1411/node-boilerplate#2]
When singing up two times with the same email nodejs throws mongodb error as follows:

![image](https://user-images.githubusercontent.com/40580801/94014709-32ff0f00-fdac-11ea-934e-5c28d07a3e36.png)

Maybe wanted?

**Comment by tillhoffmann1411** [comment]
It is correct that an error is thrown if you want to register a second time with an already existing email address. But you are right that the error must not fly here but must be caught and attracted to the user.
